version: "3.1"
services:

  code:
    container_name: code
    depends_on:
      - mysql-container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - ./baseball.sql:/data/baseball.sql
      - ./results:/results

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
#    ports:
#      - 3306:3306
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123 # pragma: allowlist secret
      MYSQL_DATABASE: baseball_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - backend

networks:
  backend: